apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user_profile
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/user_profile"
    route:
    - destination:
        host: user_profile
        port:
          number: 80
