apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fraud_detection
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/fraud_detection"
    route:
    - destination:
        host: fraud_detection
        port:
          number: 80
