apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "advancedcoupon.fullname" . }}
  labels:
    {{- include "advancedcoupon.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "advancedcoupon.selectorLabels" . | nindent 6 }}