apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      # Pod 安全上下文，定义了 Pod 级别的安全设置
      securityContext:
        runAsUser: 1000 # 运行容器的用户ID，与 Dockerfile 中的 appuser 对应
        runAsGroup: 1000 # 运行容器的组ID，与 Dockerfile 中的 appgroup 对应
        fsGroup: 1000 # 卷的所有权将更改为该组ID
      volumes:
        - name: config
          configMap:
            name: {{ include "chart.fullname" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          # 容器安全上下文，定义了容器级别的安全设置
          securityContext:
            allowPrivilegeEscalation: false # 禁止进程提升权限
            readOnlyRootFilesystem: true # 限制容器根文件系统为只读
            capabilities:
              drop:
                - ALL # 移除所有默认的 Linux 能力
          # 镜像地址和版本
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # 容器端口定义
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
          # 存活探针: 检查容器是否仍在运行。如果失败，kubelet将杀死并重启容器。
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          # 就绪探针: 检查容器是否准备好接受流量。如果失败，端点控制器将从所有服务的端点中移除Pod的IP地址。
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          # 资源请求和限制
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # 挂载配置文件
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
          # 传递给容器的启动命令
          command: ["/app/{{ .Chart.Name }}", "--conf", "/app/configs/{{ .Chart.Name }}.toml"]
