# ServiceAccount 定义
# ServiceAccount 为 Pod 提供了一个身份，用于在 Kubernetes API 中进行认证和授权。
# 为每个微服务定义一个专用的 ServiceAccount 是安全最佳实践，可以实现最小权限原则。
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }} # ServiceAccount 的名称，使用 Helm 辅助函数生成
  labels:
    {{- include "chart.labels" . | nindent 4 }} # 继承 Chart 的标签
