apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ecommerce-gateway # Istio Gateway 的名称
spec:
  selector:
    istio: ingressgateway # 选择 Istio 默认的 ingress gateway
  servers:
  - port:
      number: 80 # Gateway 监听的端口
      name: http # 端口名称
      protocol: HTTP # 协议类型
    hosts:
    - "*" # 匹配所有主机名
  # 注意: 对于生产环境，强烈建议配置 HTTPS/TLS。
  # 例如，可以添加另一个 server 配置，监听 443 端口并配置 TLS。
