apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ai_model
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/ai_model"
    route:
    - destination:
        host: ai_model
        port:
          number: 80
