apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "customer.fullname" . }
  labels:
    {- include "customer.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "customer.selectorLabels" . | nindent 6 }
