apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: data_lake_ingestion
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/data_lake_ingestion"
    route:
    - destination:
        host: data_lake_ingestion
        port:
          number: 80
