apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sales_forecasting
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/sales_forecasting"
    route:
    - destination:
        host: sales_forecasting
        port:
          number: 80
