version = "1.0.0"

[server]
name = "inventoryforecast"
environment = "dev"

[server.http]
addr = "0.0.0.0"
port = 8019
timeout = "3s"
read_timeout = "3s"
write_timeout = "3s"
idle_timeout = "60s"

[server.grpc]
addr = "0.0.0.0"
port = 9019
timeout = "3s"
max_recv_msg_size = 10485760 # 10MB
max_send_msg_size = 10485760 # 10MB

[log]
level = "info"
format = "json"
output = "stdout"
# file = "logs/inventoryforecast.log"
max_size = 100
max_backups = 3
max_age = 28

[tracing]
enabled = true
service_name = "inventoryforecast"
otlp_endpoint = "localhost:4317"

[metrics]
enabled = true
port = "18019"
path = "/metrics"

[snowflake]
start_time = "2024-01-01"
machine_id = 1


[data.database]
driver = "mysql"
dsn = "root:root@tcp(127.0.0.1:3306)/ecommerce_inventoryforecast?charset=utf8mb4&parseTime=True&loc=Local"
max_idle_conns = 10
max_open_conns = 100
conn_max_lifetime = "1h"
slow_threshold = "200ms"

[services]
