apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: settlement
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/settlement"
    route:
    - destination:
        host: settlement
        port:
          number: 80
