apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: content_moderation
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/content_moderation"
    route:
    - destination:
        host: content_moderation
        port:
          number: 80
