apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer_service
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/customer_service"
    route:
    - destination:
        host: customer_service
        port:
          number: 80
