apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wishlist.fullname" . }}-config
  labels:
    {{- include "wishlist.labels" . | nindent 4 }}
data:
  config.toml: |
    [server]
    name = "{{ .Values.image.repository }}"
    environment = "prod"