{- if .Values.autoscaling.enabled }
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: { include "aftersales.fullname" . }
  labels:
    {- include "aftersales.labels" . | nindent 4 }
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: { include "aftersales.fullname" . }
  minReplicas: { .Values.autoscaling.minReplicas }
  maxReplicas: { .Values.autoscaling.maxReplicas }
  metrics:
    {- if .Values.autoscaling.targetCPUUtilizationPercentage }
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: { .Values.autoscaling.targetCPUUtilizationPercentage }
    {- end }
{- end }
