apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aftersales.fullname" . }}
  labels:
    {{- include "aftersales.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "aftersales.selectorLabels" . | nindent 6 }}