{{- if .Values.observability.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "risksecurity.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "risksecurity.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "risksecurity.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.observability.metrics.serviceMonitor.interval }}
    honorLabels: true
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
