apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "pointsmall.fullname" . }
  labels:
    {- include "pointsmall.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "pointsmall.selectorLabels" . | nindent 6 }
