apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "multichannel.fullname" . }}
  labels:
    {{- include "multichannel.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "multichannel.selectorLabels" . | nindent 6 }}