apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loyalty.fullname" . }}
  labels:
    {{- include "loyalty.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "loyalty.selectorLabels" . | nindent 6 }}