[server]
name = "search"
environment = "dev"

[server.http]
addr = "0.0.0.0"
port = 8112
timeout = "5s"

[server.grpc]
addr = "0.0.0.0"
port = 9132
timeout = "5s"

[data.database]
driver = "mysql"
dsn = "root:password@tcp(127.0.0.1:3306)/ecommerce_search?charset=utf8mb4&parseTime=True&loc=Local"

[data.product]
addr = "localhost:9091"

[log]
level = "debug"
format = "json"
output = "stdout"

[metrics]
enabled = true
port = "9090"
path = "/metrics"
