apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ecommerce-service-template.fullname" . }}
  labels:
    {{- include "ecommerce-service-template.labels" . | nindent 4 }}
spec:
  hosts:
    - "*" # Or specify your domain, e.g., "product.ecommerce.com"
  gateways:
    - {{ include "ecommerce-service-template.fullname" . }}-gateway
  http:
    {{- range .Values.service.httpRoutes }}
    - match:
        - uri:
            prefix: {{ .match.prefix }}
      route:
        {{- if .route.subsets }}
        {{- range .route.subsets }}
        - destination:
            host: {{ include "ecommerce-service-template.fullname" $ }}
            port:
              number: {{ .port | default $.port }}
            subset: {{ .name }}
          weight: {{ .weight }}
        {{- end }}
        {{- else }}
        - destination:
            host: {{ include "ecommerce-service-template.fullname" $ }}
            port:
              number: {{ .port | default $.port }}
        {{- end }}
      {{- if .retries }}
      retries:
        attempts: {{ .retries.attempts }}
        perTryTimeout: {{ .retries.perTryTimeout }}
        retryOn: {{ .retries.retryOn }}
      {{- end }}
      {{- if .fault }}
      fault:
        {{- if .fault.delay }}
        delay:
          percentage:
            value: {{ .fault.delay.percentage }}
          fixedDelay: {{ .fault.delay.fixedDelay }}
        {{- end }}
        {{- if .fault.abort }}
        abort:
          percentage:
            value: {{ .fault.abort.percentage }}
          httpStatus: {{ .fault.abort.httpStatus }}
        {{- end }}
      {{- end }}
      {{- if .mirror }}
      mirror:
        host: {{ .mirror.host }}
        port:
          number: {{ .mirror.port }}
      mirrorPercentage:
        value: {{ .mirror.percentage }}
      {{- end }}
    {{- end }}
