apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "ecommerce-service-template.fullname" . }}-gateway
  labels:
    {{- include "ecommerce-service-template.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway # Use Istio's default ingress gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*" # Or specify your domain, e.g., "product.ecommerce.com"
