apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "file.fullname" . }}
  labels:
    {{- include "file.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "file.selectorLabels" . | nindent 6 }}