{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  hosts:
  {{- if .Values.istio.gateway.enabled }}
  {{- range .Values.istio.gateway.hosts }}
  - {{ . | quote }}
  {{- end }}
  {{- else }}
  - {{ include "fullname" . }}
  {{- end }}
  {{- if .Values.istio.gateway.enabled }}
  gateways:
  - {{ include "fullname" . }}-gateway
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /api/v1/{{ .Chart.Name }}
    route:
    - destination:
        host: {{ include "fullname" . }}
        port:
          number: {{ .Values.service.httpPort }}
  - match:
    - uri:
        prefix: /{{ .Values.service.grpcService }}
    route:
    - destination:
        host: {{ include "fullname" . }}
        port:
          number: {{ .Values.service.grpcPort }}
{{- end }}
