apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: realtime_analytics
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/realtime_analytics"
    route:
    - destination:
        host: realtime_analytics
        port:
          number: 80
