apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: marketing
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/marketing"
    route:
    - destination:
        host: marketing
        port:
          number: 80
