[server.http]
addr = "0.0.0.0"
port = 8100
timeout = "1s"

[server.grpc]
addr = "0.0.0.0"
port = 9120
timeout = "1s"

[data.database]
driver = "mysql"
dsn = "root:your_password@tcp(127.0.0.1:3306)/ecommerce_logistics_routing?charset=utf8mb4&parseTime=True&loc=Local"

[log]
level = "debug"
format = "json"
output = "stdout"
