{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "user.fullname" . }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
spec:
  host: {{ include "user.fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- end }}
