[server]
name = "loyalty"
environment = "dev"

[server.http]
addr = "0.0.0.0"
port = 8119
timeout = "1s"

[server.grpc]
addr = "0.0.0.0"
port = 9139
timeout = "1s"

[data.database]
driver = "mysql"
dsn = "root:your_password@tcp(127.0.0.1:3306)/ecommerce_loyalty?charset=utf8mb4&parseTime=True&loc=Local"

[log]
level = "debug"
format = "json"
output = "stdout"

[metrics]
enabled = true
port = "9090"
path = "/metrics"
