apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "settlement.fullname" . }
  labels:
    {- include "settlement.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "settlement.selectorLabels" . | nindent 6 }
