{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  host: {{ include "fullname" . }}
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
{{- end }}
