apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "dynamicpricing.fullname" . }
  labels:
    {- include "dynamicpricing.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "dynamicpricing.selectorLabels" . | nindent 6 }
