apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "gateway.fullname" . }
  labels:
    {- include "gateway.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "gateway.selectorLabels" . | nindent 6 }
