# Aftersales Service Configuration
[service]
name = "aftersales"
version = "1.0.0"
port = 8087

[database]
host = "localhost"
port = 3306
user = "root"
password = "password"
dbname = "aftersales_db"

[logging]
level = "info"
