# CMS Service Configuration
[service]
name = "cms"
version = "1.0.0"
port = 8085

[database]
host = "localhost"
port = 3306
user = "root"
password = "password"
dbname = "cms_db"

[logging]
level = "info"
