[server]
  [server.grpc]
    addr = "0.0.0.0"
    port = 8022
  [server.http]
    addr = "0.0.0.0"
    port = 8102

[log]
  level = "info"
  format = "console"
  output = "stdout"

[data]
  # No specific database for data lake ingestion, it writes to a simulated file
