[server]
  [server.grpc]
    addr = "0.0.0.0"
    port = 8003
  [server.http]
    addr = "0.0.0.0"
    port = 8083

[log]
  level = "info"
  format = "console"
  output = "stdout"

[data]
  # No specific database for data ingestion, it writes to a simulated data lake
