[server]
  [server.grpc]
    addr = "0.0.0.0"
    port = 8021
  [server.http]
    addr = "0.0.0.0"
    port = 8101

[log]
  level = "info"
  format = "console"
  output = "stdout"

[data]
  # No specific database for data warehouse query, it simulates queries
