[server]
  [server.grpc]
    addr = "0.0.0.0"
    port = 8024
  [server.http]
    addr = "0.0.0.0"
    port = 8104

[log]
  level = "info"
  format = "console"
  output = "stdout"

[data]
  # Real-time analytics data is in-memory for simulation
  [data.kafka]
    brokers = ["127.0.0.1:9092"]
    topic = "cdc_events" # Consuming CDC events
    group_id = "realtime_analytics_consumer_group"
    dial_timeout = "5s"
    read_timeout = "5s"
    write_timeout = "5s"

[services]
  [services.user_profile]
    addr = "127.0.0.1:8019"
