[server]
  [server.grpc]
    addr = "0.0.0.0"
    port = 8019
  [server.http]
    addr = "0.0.0.0"
    port = 8099

[log]
  level = "info"
  format = "console"
  output = "stdout"

[data]
  [data.hbase]
    zookeeper_quorum = ["127.0.0.1:2181"]
    root_znode = "/hbase"
    timeout = "5s"
