apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "groupbuy.fullname" . }}
  labels:
    {{- include "groupbuy.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "groupbuy.selectorLabels" . | nindent 6 }}