apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "inventory.fullname" . }}
  labels:
    {{- include "inventory.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "inventory.selectorLabels" . | nindent 6 }}