apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "recommendation.fullname" . }}
  labels:
    {{- include "recommendation.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "recommendation.selectorLabels" . | nindent 6 }}