apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "inventoryforecast.fullname" . }}
  labels:
    {{- include "inventoryforecast.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "inventoryforecast.selectorLabels" . | nindent 6 }}