{- if .Values.serviceAccount.create -}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: { include "inventoryforecast.serviceAccountName" . }
  labels:
    {- include "inventoryforecast.labels" . | nindent 4 }
  {- with .Values.serviceAccount.annotations }
  annotations:
    {- toYaml . | nindent 4 }
  {- end }
{- end }
