apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: data_warehouse_query
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/data_warehouse_query"
    route:
    - destination:
        host: data_warehouse_query
        port:
          number: 80
