apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "payment.fullname" . }}
  labels:
    {{- include "payment.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "payment.selectorLabels" . | nindent 6 }}