apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "permission.fullname" . }
  labels:
    {- include "permission.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "permission.selectorLabels" . | nindent 6 }
