apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: { include "contentmoderation.fullname" . }
  labels:
    {- include "contentmoderation.labels" . | nindent 4 }
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {- include "contentmoderation.selectorLabels" . | nindent 6 }
