apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: data_processing
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/data_processing"
    route:
    - destination:
        host: data_processing
        port:
          number: 80
