apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: smart_product_selection
spec:
  hosts:
  - "*"
  gateways:
  - ecommerce-gateway
  http:
  - match:
    - uri:
        prefix: "/api/smart_product_selection"
    route:
    - destination:
        host: smart_product_selection
        port:
          number: 80
